version: "3.9"

services:
  backend:
    build:
      context: ./backend-omninotify
    container_name: omninotify-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend-omninotify/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend_omninotify
    container_name: omninotify-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
